### ISSUE TITLE
[PE-D][Tester A] listing add allows duplicate prefixes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-3/tp#318] opened 2024-11-08 23:50 UTC
If the command input is `add listing 1 t/HDB a/address1 t/office  a/address2` no error is thrown, only the last tag and address is captured by the application. This may cause confusion to the users as there is no error message when there is duplicate prefixes.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: DesSnowy/ped#16

**Comment by Tkaixiang** [comment] 2024-11-09 10:23
Marked as not a bug since
"the current behavior inconveniences the user but there is a way to work around it."

We will add a clarification to the UG instead

**Closed** 2024-11-10 10:51 UTC
Labels: type.wontfix
