### ISSUE TITLE
[PE-D][Tester A] `show` still shows contact details after deletion

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#246] opened 2024-11-08 16:38 UTC
When a contact detail is shown before it gets deleted, the contact details of the deleted person is still shown, causing users to assume that the user is still there. 

Details of David Li is still shown after being deleted:
![image.png](https://raw.githubusercontent.com/DesSnowy/ped/main/files/6355ab0d-9c67-4fa7-b846-8ec2ca34229c.png)

Finding for Davind Li shows no result despite his details being shown:

![image.png](https://raw.githubusercontent.com/DesSnowy/ped/main/files/14e2aaed-af23-4306-a5c5-14edab117287.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: DesSnowy/ped#2

**Comment by sayomaki** [comment] 2024-11-09 10:07
Hi @DesSnowy, thanks for reporting this issue! Definitely, the right side of the interface will still show the last contact/person to be shown, and it works as intended to show the correct contact/person even if the contact/person is deleted. 

Running the show command again with a different person will replace the view with the new contact/person, and I believe that this is just a minor detail that may not even cause any inconveniences for the user at all. I really appreciate you for being meticulous and spotting this!

**Comment by Tkaixiang** [comment] 2024-11-09 10:53
Fixed in #323

**Closed** 2024-11-10 10:53 UTC
Labels: type.Bug
