### ISSUE TITLE
[PE-D][Tester A] User story not matching

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-3/tp#319] opened 2024-11-08 23:52 UTC
![image.png](https://raw.githubusercontent.com/DesSnowy/ped/main/files/673512ec-bd29-479c-a299-cad07d4c8a4a.png)

In the user story shown, knowing the types of tags does not match with keeping track of client preferences. A better function could be similar to being able to add tags to the contacts.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DesSnowy/ped#17

**Comment by Vatinius** [comment] 2024-11-09 06:40
I feel we can close this as it is classified under `good to have`

**Comment by tayxuenye** [comment] 2024-11-09 14:14
Since it's labelled good to have, we will just leave it there. Not a bug.

**Closed by tayxuenye** 2024-11-09 14:14 UTC
Labels: type.Discuss
